### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by starptr** [jprjr/spc2wav#1]
Hey cool project, the release binaries work but you don't have an arm64 osx build, so I was trying to build it from source. I'm also thinking about repackaging it for Nix. How do I build this project correctly?

What I tried so far:
I found a copy of `snes_spc` on [Wayback](https://web.archive.org/web/20110812132836/http://blargg.parodius.com/libs/snes_spc-0.9.0.zip) and also copied your [libid666](https://github.com/jprjr/libid666) library into the root (renamed `libid666` to `id666`), and changed the `#include`s in `spc2wav.c` to quote-includes accordingly. But I'm still having build issues (`snes_spc_t` isn't defined anywhere).

**Comment by jprjr** [comment]
Hi there! So when I first wrote this, I was using my own fork of `snes_spc`, and at some point in my fork I renamed the `SNES_SPC` struct to `snes_spc_t` in the C headers. Looking back - I'm unsure why.

I'm going to update my fork to remain more compatible with the original `snes_spc` to allow building `spc2wav` against both.

As far as proper build instructions - my general expectation is the dependent libraries are built and installed with whatever OS package management is appropriate - so Nix, arch's PKGBUILD, etc.

**Comment by jprjr** [comment]
I've updated my own `snes_spc` fork to be API-compatible with version 0.9.0, and updated `spc2wav` accordingly.

I also restructured `libid666` to allow easier in-tree building, without having to rename the cloned folder.

I added a small Makefile sample to the README of `spc2wav` that can build `snes_spc` version 0.9.0 as a shared + static library and install it.

Building is really up to packagers. Make is pretty flexible, you have a few different options for building this. I tried to keep the code as simple/straightforward as possible to not rely on a lot of compiler/linker flags, so it should be easy to import to any C environment. You shouldn't have to alter any source files to build this.

So - create packages for `snes_spc` and `libid666`, install them. Assuming those packages create a `libspc.a` or `libspc.so` file under the usual linker search paths (`/usr/lib`, `/usr/local/lib`, etc), and place the `snes_spc/spc.h` header in one of the usual include paths (`/usr/include/snes_spc/spc.h`) - and assuming you're using GCC or Clang, you should be able to just run `make`.

Alternatively you could clone the latest `snes_spc` and `libid666` to the root of the repo and just change the CFLAGS and LDFLAGS variables as appropriate. Again this example is assuming a Unix-ish environment with git, and gcc or clang:

```bash
git clone https://github.com/jprjr/spc2wav
cd spc2wav
git clone https://github.com/jprjr/snes_spc
git clone https://github.com/jprjr/libid666
make -C snes_spc
make -C libid666
make CFLAGS="-Isnes_spc -Ilibid666 -O2 -Wall -Wextra" LDFLAGS="-Lsnes_spc -lspc -Llibid666 -lid666 -static"
```

Hope that helps!

**Comment by starptr** [comment]
This is awesome, thanks for such a thorough answer!
A note for posterity for osx users: I didn't investigate this much further because I just installed the libraries globally, but I tried statically linking to snes_spc libid666 like you suggested at the end at first, but I couldn't get the linker to work (probably because of [this](https://stackoverflow.com/a/3801032)).
